// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwcqjvyykkmvkcllwakp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3Y3Fqdnl5a2ttdmtjbGx3YWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjY1MjYsImV4cCI6MjA2NDMwMjUyNn0.Gk8YNpGeYyzHYJT7zks8yjyAHf0zVletRGhJ0AdESDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);